### ISSUE TITLE
Would you support a PR for including multiple repos?

### ISSUE THREAD

**Issue by gjtorikian** [stephenyeargin/hubot-github-deployments#32]
Hi there! Rather than support an environment variable for repo selection (`HUBOT_GITHUB_REPO`), I'm interested in putting up a PR that would handle the repo based on text in the command. These might look like `hubot deploy status for owner/repo` or `hubot deploy <branch or SHA> to <server> for owner/repo`.

The use case for this is that we have Hubot several repos on our org, and we have several repos to deploy. 

The `for owner/repo` syntax would be optional, and if it's missing, the environment variable will be used instead. What do you think?

**Comment by stephenyeargin** [comment]
That makes sense. When this was originally written, it was intended as a way of demonstrating the practical uses for the GitHub Deployments API, and I worked at a company with a monolithic app to deploy. I think it's a good idea to build in backwards compatibility for folks that have it set up in that manner.
