### ISSUE TITLE
409 on deploy

### ISSUE THREAD

**Issue by dennybaa** [stephenyeargin/hubot-github-deployments#39]
Howdy, maybe you could give me a clue. I do `bot deploy v-test to stage`.

and get a strange response such as bellow:
`[Thu Mar 18 2021 18:20:56 GMT+0000 (Coordinated Universal Time)] ERROR 409 Conflict merging dev into v-test`

dev it's my default branch while v-test is a tag... Not very close with gh deployments and its API, but I'm definitely misleaded by this response...

**Comment by stephenyeargin** [comment]
I'm going to guess the error may have to do with your other tooling. Perhaps there's a step where, after a deployment event is received, it attempts to rebase/merge with the default branch prior to deploying? This script was written in such a way that it doesn't have to know much about your deploy process itself.

**Comment by dennybaa** [comment]
Here's what I found
https://docs.github.com/en/rest/reference/repos#create-a-deployment--parameters, I believe params should be under control at least `auto_merge`.

**Comment by stephenyeargin** [comment]
Ah nice. Back when I first wrote this, none of those options were available. It basically just wrote to a message bus for another application to read/write. They seem to have made it smarter.

I'll take a look at your PR.
