### ISSUE TITLE
Hubot Versioning

### ISSUE THREAD

**Issue by johnseekins-pathccm** [stephenyeargin/hubot-github-deployments#54]
Following Hubot's recommended setup pattern (https://hubot.github.com/docs/), I end up with Hubot 9.x installed, which this package (and your Dad Jokes package, which we sorely need) doesn't support because you pin Hubot to `3 || 4`.

Is it possible to update the peer dependency safely?

**Comment by stephenyeargin** [comment]
@johnseekins-pathccm Howdy! Should be good to go with [v1.2.14](https://github.com/stephenyeargin/hubot-github-deployments/releases/tag/v1.2.14).

**Comment by stephenyeargin** [comment]
Here's [`hubot-dad-jokes`](https://github.com/stephenyeargin/hubot-dad-jokes/releases/tag/v1.0.11) as well. 😆
